backend:
  name: github
  repo: wjaelee/woongjaelee.com

media_folder: static/assets
public_folder: assets

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_data/blog'
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    create: true
    slug: '{{slug}}'
    fields:
      - label: 'Category'
        name: 'category'
        widget: 'string'
        default: 'blog'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Description'
        name: 'description'
        widget: 'string'
      - label: 'Date'
        name: 'date'
        widget: 'datetime'
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
      - label: 'Published'
        name: 'published'
        widget: 'boolean'
        default: true
      - label: 'Cover'
        name: 'cover'
        widget: 'image'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
  - name: 'education'
    label: 'Education'
    folder: '_data/education'
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    create: true
    slug: '{{slug}}'
    fields:
      - label: 'Category'
        name: 'category'
        widget: 'string'
        default: 'education'
      - label: 'University'
        name: 'university'
        widget: 'string'
      - label: 'Degree'
        name: 'degree'
        widget: 'string'
      - label: 'Start Date'
        name: 'startDate'
        widget: 'string'
      - label: 'End Date'
        name: 'endDate'
        widget: 'string'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
  - label: 'Site Metadata'
    name: 'site-metadata'
    files:
      - label: 'About Page'
        name: 'about'
        file: '_data/site-metadata/about.md'
        fields:
          - { label: Category, name: category, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - label: 'Blog Page'
        name: 'blog-page'
        file: '_data/site-metadata/blog.md'
        fields:
          - { label: Category, name: category, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
      - label: 'Projects Page'
        name: 'projects'
        file: '_data//projects.md'
        fields:
          - { label: Category, name: category, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
      - label: 'Resume - Work Experience'
        name: 'work experience'
        file: '_data/site-metadata/resume-work-experience.md'
        fields:
          - { label: Category, name: category, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
      - label: 'Resume - Research'
        name: 'research'
        file: '_data/site-metadata/research.md'
        fields:
          - { label: Category, name: category, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
      - label: 'Resume - Education'
        name: 'education'
        file: '_data/site-metadata/education.md'
        fields:
          - { label: Category, name: category, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
      - label: 'Resume - Skills'
        name: 'skills'
        file: '_data/site-metadata/skills.md'
        fields:
          - { label: Category, name: category, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
      - label: 'Landing - Introduction'
        name: 'introduction'
        file: '_data/site-metadata/introduce-myself.md'
        fields:
          - { label: Category, name: category, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Content, name: content, widget: string }
          - { label: Link to, name: linkTo, widget: string }
          - { label: Link Text, name: linkText, widget: string }
      - label: 'Landing - Recent Blog Posts'
        name: 'recent blog posts'
        file: '_data/site-metadata/recent-blog-posts.md'
        fields:
          - { label: Category, name: category, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Link to, name: linkTo, widget: string }
          - { label: Link Text, name: linkText, widget: string }
      - label: 'Landing - Life Updates'
        name: 'life updates'
        file: '_data/site-metadata/life-updates.md'
        fields:
          - { label: Category, name: category, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
      - label: 'Newsletter'
        name: 'newsletter'
        file: '_data/site-metadata/newsletter.md'
        fields:
          - { label: Category, name: category, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: NamePlaceholder, name: namePlaceholder, widget: string }
          - { label: EmailPlaceholder, name: emailPlaceholder, widget: string }
          - { label: SubmitPlaceholder, name: submitPlaceholder, widget: string }
